# Generated by Django 3.2.2 on 2021-05-30 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_product_typepd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='typePD',
            field=models.CharField(blank=True, choices=[('CPU', 'Cpu'), ('Mainboard', 'Mainboard'), ('RAM', 'Ram'), ('VGA', 'Vga'), ('PSU', 'Psu'), ('Case', 'Case'), ('HDD', 'Hdd'), ('SSD', 'Ssd'), ('LCD', 'Lcd'), ('Keyboard', 'Keyboard'), ('Mouse', 'Mouse'), ('Headphone', 'Headphone'), ('Chair', 'Chair'), ('Accessories', 'Accessories')], max_length=20),
        ),
    ]
