# Generated by Django 3.2.2 on 2021-05-30 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_product_typepd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prices',
            field=models.IntegerField(),
        ),
    ]
