# Generated by Django 3.2.2 on 2021-05-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_product_typepd'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='productname',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
