# Generated by Django 3.2.2 on 2021-05-30 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_orderitem_productname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='typePD',
            field=models.CharField(blank=True, choices=[('CPU', 'Cpu'), ('Mainboard', 'Mainboard'), ('RAM', 'Ram'), ('VGA', 'Vga'), ('PSU', 'Psu'), ('Case', 'Case')], max_length=10),
        ),
    ]
